# --- Tahap 1: Build Aplikasi Vue.js ---
FROM node:20-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# --- Tahap 2: Sajikan dengan Web Server Nginx ---
FROM nginx:stable-alpine

# Salin dari folder "dist" (hasil build Vue) ke direktori Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]