# Gunakan base image Node.js yang ringan
FROM node:20-alpine

# Tentukan direktori kerja di dalam container
WORKDIR /app

# Salin file package.json terlebih dahulu untuk optimasi cache
COPY package*.json ./

# Instal semua dependensi yang dibutuhkan
RUN npm install

# Salin sisa kode aplikasi Anda
COPY . .

# Beri tahu Docker bahwa aplikasi berjalan di port 5000
EXPOSE 5000

# Perintah default untuk menjalankan aplikasi
CMD [ "node", "src/server.js" ]